name: All Builds (Linux, macOS, Windows, Android, APK, AAB)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli

    - name: Create pubspec.yaml
      run: |
        cat > pubspec.yaml << 'EOF'
        name: home_services
        description: تطبيق خدمات منزلية متكاملة
        version: 1.0.0+1

        environment:
          sdk: '>=3.0.0 <4.0.0'

        dependencies:
          flet: ^0.28.3
          flutter:
            sdk: flutter

        dev_dependencies:
          flutter_test:
            sdk: flutter

        flutter:
          uses-material-design: true
        EOF

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Accept Android licenses
      run: |
        flutter doctor --android-licenses

    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: home-services-apk
        path: build/apk/*.apk
